services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - mongo-dev
    # Uncomment the following line to keep the container running
    # command: >
    #   ash -c '
    #     /usr/bin/tail -f /dev/null
    #   '

  mongo-dev:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db

volumes:
  mongo-dev-data:
