services:
  prod:
    build:
      context: ..
      dockerfile: docker/prod.Dockerfile
    env_file:
      - ../.env
    depends_on:
      - mongo-prod

  mongo-prod:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-prod-data:/data/db

volumes:
  mongo-prod-data:
