services:
  app:
    build:
      context: ..
      dockerfile: docker/prod.Dockerfile
    env_file:
      - ../.env

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
