services:
  test:
    build:
      context: ..
      dockerfile: docker/test.Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - mongo-test

  mongo-test:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-test-data:
